version: '3'

services:

  server-102t:
    build: ./docker-openssl/1.0.2t
    container_name: server-102t
    tty: true
    networks:
      - tls
    expose:
      - 443
    volumes:
      - ./cert:/cert
      - ./keylog:/keylog
    command: s_server -key /cert/key.pem -cert /cert/cert.pem -accept 443 -www

  server-111d:
    build: ./docker-openssl/1.1.1d
    container_name: server-111d
    tty: true
    networks:
      - tls
    expose:
      - 443
    volumes:
      - ./cert:/cert
      - ./keylog:/keylog
    command: s_server -key /cert/key.pem -cert /cert/cert.pem -accept 443 -www -keylogfile /keylog/key.log

  client-102t:
    build: ./docker-openssl/1.0.2t
    container_name: client-102t
    tty: true
    networks:
      - tls

  client-111d:
    build: ./docker-openssl/1.1.1d
    container_name: client-111d
    tty: true
    networks:
      - tls

networks:
  tls:
