version: "3.7"

services:

  app:
    build: ./app
    container_name: tls-app
    #restart: always
    volumes: 
      - ./app/src:/tls/app
      - ../scripts/results/:/tls/app/downloads/results
    networks:
      - app
      - db
    ports:
      - 5000:5000
    env_file: ./.env
    links:
      - db:db
    depends_on:
      - db

  db:
    image: mysql
    container_name: tls-db
    #restart: always
    networks:
      - db
    expose:
      - 3306
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password

networks:
  app:
    name: tls-app
  db:
    name: tls-db